### ISSUE TITLE
peer.stream is undefined

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-floodsub#11] opened 2016-12-14 19:43 UTC
I've been debugging orbit in the browser and found this happens regularly.

The situation is as follows, in https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/mount-floodsub.js#L87 `peer` does not always have a `stream` property, resulting in an error in this line when being called. Not sure how this should be handled. 

Full error stack

```
temp1.stack
"TypeError: Cannot read property 'write' of undefined
    at http://localhost:8081/assets/app.js:118950:28
    at Array.forEach (native)
    at http://localhost:8081/assets/app.js:118944:19
    at Array.forEach (native)
    at http://localhost:8081/assets/app.js:118924:20
    at http://localhost:8081/assets/app.js:17083:37
    at callback (http://localhost:8081/assets/app.js:41828:5)
    at Function.read.push (http://localhost:8081/assets/app.js:41795:7)
    at http://localhost:8081/assets/app.js:228914:11
    at http://localhost:8081/assets/app.js:228979:9
    at Object.cb (http://localhost:8081/assets/app.js:228991:5)
    at drain (http://localhost:8081/assets/app.js:79580:14)
    at more (http://localhost:8081/assets/app.js:79592:13)
    at Function.reader.read (http://localhost:8081/assets/app.js:79636:7)
    at readMessage (http://localhost:8081/assets/app.js:228986:10)
    at Object.cb (http://localhost:8081/assets/app.js:228972:7)"
```

```
> peerSet
Object
  QmTC1tFbAeZna8tJFBWiyUX4GFNn28yFxBB5Bo9P17uFFb : Object
    conn : Connection
    peerInfo : PeerInfo
    stream : PassThrough
    topics : Array[1]
    __proto__ : Object
  QmWXDLc7BEMdehrhhqsf5bUwGPuvegDM5QzwbGM4Qi3NNV : Object
    conn : Connection
    peerInfo : PeerInfo
    stream : PassThrough
    topics : Array[1]
    __proto__ : Object
  QmWcSesZ1ERsBLvrePfCVEdYx23pV2XicGaZN3snFqTW6e : Object
    conn : Connection
    peerInfo : PeerInfo
    stream : PassThrough
    topics : Array[2]
    __proto__ : Object
  QmZn1hVkpLgnfd4baSzkFn7KrDSs8h9tRvycatJFDXXP78 : Object
    conn : Connection
    peerInfo : PeerInfo
    stream : PassThrough
    topics : Array[0]
    __proto__ : Object
  QmbB3e8pi7mMqMwEUUCwL3E7CRC2gakUkEitRq9m1QPAwV : Object
    conn : Connection
    peerInfo : PeerInfo
    stream : PassThrough
    topics : Array[1]
    __proto__ : Object
  QmcXJM45d7S6bP2hr43DCy2LH6cLjzcHt1uuZEpjhRq2DJ : Object
    peerInfo : PeerInfo
    topics : Array[3]
    __proto__ : Object
  QmeLcFFq9iLL5uwt3E3196Ch9nVDKC1Jm2jPJRmizMYHD7 : Object
    peerInfo : PeerInfo
    topics : Array[3]
    __proto__ : Object
__proto__ : Object
```

**Comment by dignifiedquire** [comment] 2016-12-14 19:44
ref https://github.com/haadcode/orbit/issues/210#issuecomment-267135609

**Comment by dignifiedquire** [comment] 2016-12-14 19:44
cc @diasdavid @haadcode

**Comment by haadcode** [comment] 2016-12-16 13:13
Sorry, not familiar with this part of the code. @gavinmcdermott might also have an idea.

**Comment by diasdavid** [comment] 2016-12-16 19:49
This is caused by having incoming pubsub dials (receiving messages or subscriptions), without having yet dialed stream (to send messages and subscriptions). A simple check on the for forEach loop -- https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L65 -- to see if 'we already dialed' would solve this issue.

**Comment by diasdavid** [comment] 2016-12-18 09:46
fixed with https://github.com/libp2p/js-libp2p-floodsub/pull/12 , thank you @dignifiedquire :)

**Closed** 2016-12-18 09:46 UTC
